"""tabela de contas bancárias

Revision ID: 0b75df52849d
Revises: 0c115b19c713
Create Date: 2018-11-16 17:32:59.000633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b75df52849d'
down_revision = '0c115b19c713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sum_on_dash', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_created_at'), 'account', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_account', sa.Integer(), nullable=True),
    sa.Column('to_account', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observation', sa.String(length=150), nullable=True),
    sa.Column('transfer_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['to_account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_transfer_date'), 'transfer', ['transfer_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_transfer_date'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_index(op.f('ix_account_created_at'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
